doctrine:
    dbal:
        server_version: 'mariadb-10.4.8'
        url: 'mysql://%env(resolve:DATABASE_USERNAME)%:%env(resolve:DATABASE_PASSWORD)%@%env(resolve:DATABASE_HOST)%:3306/%env(resolve:DATABASE_NAME)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

